# Ket noi Database AITasker_Thao
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=AITasker_Thao;user=sa;password=123456;encrypt=true;trustServerCertificate=true;
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Cau hinh Hibernate / JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
server.port=8089